version: '3.1'

services:
  wordpress:
    image: bitnami/wordpress:latest
    environment:
      - WORDPRESS_DATABASE_HOST=mysql
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: bitnami/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - mysql_data:/bitnami/mysql

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=redis_password
    volumes:
      - redis_data:/bitnami/redis

  nginx:
    image: bitnami/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress.conf
    depends_on:
      - wordpress

volumes:
  wordpress_data:
  mysql_data:
  redis_data:
